config/routes.rb
Rails.application.routes.draw do

  root 'tags#index'

  # Tags
  get 'tags' => 'tags#index'
  get 'tags/new' => 'tags#new'
  get 'tags/:id' => 'tags#show', as: :tag
  post 'tags' => 'tags#create'
  get 'tags/:id/edit' => 'tags#edit', as: :edit_tag
  patch 'tags/:id' => 'tags#update'
  delete 'tags/:id' => 'tags#destroy'
  resources :tags

  # Base Plants
  get 'plants' => 'plants#index'
  get 'plants/new' => 'plants#new'
  get 'plants/:id' => 'plants#show', as: :plant
  post 'plants' => 'plants#create'
  get 'plants/:id/edit' => 'plants#edit', as: :edit_plant
  patch 'plants/:id' => 'plants#update'
  delete 'plants/:id' => 'plants#destroy'
  resources :plants

  # Custom user plants
  get 'users/:id' => 'users#show'
  get 'users/:id/new' => 'user_plants#new'
  get 'userplants/:id' => 'user_plants#show', as: :user_plant
  post 'users/:id/' => 'user_plants#create'
  get 'userplants/:id/edit' => 'user_plants#edit', as: :edit_user_plant
  patch 'userplants/:id' => 'user_plants#update'
  delete 'userplants/:id' => 'user_plants#destroy'
  resources :user_plants


  # Signup and login
  get 'signup' => 'users#new'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :tag
  belongs_to :plant
end

app/models/plant.rb
# A plant. Each instance holds properties true across all copies of that plant.
class Plant < ApplicationRecord
  has_many :entries
  has_many :tags, through: :entries
  has_many :user_plants

  def tag_list
    string = ''
    tags.each { |t| string += "#{t.name}, " }
    string
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :entries
  has_many :plants, through: :entries
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :user_plants
end

app/models/user_plant.rb
class UserPlant < ApplicationRecord
  belongs_to :user
  belongs_to :plant

  def start_time
    last_watered.to_date + plant.watering_time.days
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :require_user, only: %i[destroy new edit]

  def index
    @plants = Plant.all
  end

  def show
    @plant = Plant.find(params[:id])
    @tags = @plant.tags
  end

  def new
    @plant = Plant.new
  end

  def create
    @plant = Plant.new(full_params)
    if @plant.save
      redirect_to '/plants'
    else
      render 'new'
    end
  end

  def edit
    @plant = Plant.find(params[:id])
  end

  def update
    @plant = Plant.find(params[:id])
    if @plant.update_attributes(full_params)
      redirect_to(action: 'show', id: @plant.id)
    else
      render 'edit'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to '/plants'
  end

  helper_method :all_tags
  def all_tags
    tags = Tag.all
    tags.each { |t| { name: t.name, id: t.id } }
  end

  helper_method :tag_list
  def tag_list
    plant = Plant.find(params[:id])
    plant.tags.each { |t| { name: t.name, id: t.id } } # TODO: convert to proc
  end

  private

  def full_params
    params = plant_params

    # Get tags from IDs
    tag_ids = params[:tag_list]
    tags = tag_ids.split(',').collect { |t| Tag.find(t) }

    # Replace IDs with instances
    params.delete(:tag_list)
    params[:tags] = tags
    params
  end

  def plant_params
    params.require(:plant).permit(:name, :common_names, :watering_time,
                                  :sunlight_exposure, :summer_environment,
                                  :winter_environment, :description, :info_link,
                                  :tag_list)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by_username(params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @plants = @tag.plants
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    redirect_to '/tags'
  end
end

app/controllers/user_plants_controller.rb
class UserPlantsController < ApplicationController
  before_action :require_user, only: %i[index show destroy new edit]


  def show
    @user_plant = UserPlant.find(params[:id])
  end

  def new
    @user_plant = UserPlant.new
  end

  def create
    @user_plant = UserPlant.new(full_params)

    if @user_plant.save
      redirect_to "/users/#{current_user.id}"
    else
      render 'new'
    end
  end

  def edit
    @user_plant = UserPlant.find(params[:id])
  end

  def update
    @user_plant = UserPlant.find(params[:id])
    if @user_plant.update_attributes(full_params)
      redirect_to(action: 'show', id: @user_plant.id)
    else
      render 'edit'
    end
  end

  def destroy
    @user_plant = UserPlant.find(params[:id])
    @user_plant.destroy
    redirect_to "/users/#{current_user.id}"
  end

  private

  def full_params
    params = user_plant_params

    # Fetch plant and user from ID
    params[:plant] = Plant.find(params[:plant])
    params[:user] = current_user

    params
  end

  def user_plant_params
    params.require(:user_plant).permit(:plant, :user, :custom_name,
                                       :notes, :last_watered)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: %i[index show destroy]

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @user_plants = @user.user_plants
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/user_plants_helper.rb
module UserPlantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plants!</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.2/css/mdb.min.css" type="text/css">-->
    <script src="https://twitter.github.io/typeahead.js/releases/latest/typeahead.bundle.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-year-calendar/1.1.1/css/bootstrap-year-calendar.min.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-year-calendar/1.1.1/js/bootstrap-year-calendar.min.js"></script>
  </head>

  <body>
  <nav class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapsable">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">Plants!</a>
      </div>
      <div class="collapse navbar-collapse" id="navbar-collapsable">
        <ul class="nav navbar-nav foo" id="menu">
          <li><a href="/">Plant Database</a></li>
          <li><a href="/plants/new">Add Plant</a></li>
          <li>
            <a href="/contact">Contact Us!</a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stuff <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li class="dropdown-header">Great stuff!</li>
              <li><a href="/one">One</a></li>
              <li><a href="/two">Two</a></li>
              <li><a href="/three">Three</a></li>
              <li class="divider"></li>
              <li><a href="/admin">Admin Dashboard</a></li>
              <li><a href="/admin/users">Users</a></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right" align="right">
          <% if current_user %>
              <li class="navbar-text"><%= "Hello, #{current_user.username}" %></li>
              <li><%= link_to 'Profile', user_path(current_user) %></li>
              <li><%= link_to 'Log out', logout_path, method: 'delete' %></li>
          <% else %>
              <li><%= link_to 'Login', 'login' %></a></li>
              <li><%= link_to 'Sign up', 'signup' %></a></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
		<div id="main-container" class="container">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>
  <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.3.2/js/mdb.min.js"></script>-->
  </body>
</html>

app/views/plants/edit.html.erb
<script>
    allTags = <%= raw all_tags.to_json %>;
    currentTags = <%= raw tag_list.to_json %>;
</script>

<div class="col-md-4 col-md-offset-4">
  <h2>Editing: <%= @plant.name %></h2>
  <%= bootstrap_form_for(@plant) do |f| %>
  <div class="field">
    <%= f.text_field :name %>
    <%= f.text_field :common_names %>
    <%= f.label :common_names, 'Please separate each name with a comma' %>
  </div>
  <br>
  <div class="field">
    <%= f.number_field :watering_time %>
    <%= f.label :watering_time, 'Days between watering' %>
  </div>
  <br>
  <div class="field">
    <%= f.select :sunlight_exposure, [['Shade', 0], ['Partial Shade', 1], ['Partial Light', 2], ['Direct Light', 3]] %>
    <%= f.select :summer_environment, [['Indoors', 0], ['Outdoors', 1], ['Either', 2]] %>
    <%= f.select :winter_environment, [['Indoors', 0], ['Outdoors', 1], ['Either', 2]] %>
  </div>
  <br>
  <div class="field">
    <%= f.text_area :description %>
    <%= f.text_field :info_link %>
  </div>
  <div class="field">
    <%= f.text_field :tag_list, 'data-role'=>'tagsinput', id: 'tags' %>
    <script>
      var tagNames = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: allTags
      });

      var input = $('#tags');
      input.tagsinput({
          itemValue: 'id',
          itemText: 'name',
          maxTags: 3,
          trimValue: true,
          cancelConfirmKeysOnEmpty: true,
          typeaheadjs: {
              highlight: true,
              name: 'tags',
              display: 'name',
              source: tagNames.ttAdapter()
          }
      });

      for(var i in currentTags) input.tagsinput('add', currentTags[i]);
    </script>
  </div>
  <div class="actions">
    <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
        <i class="icon-ok icon-white"></i> Save Changes
    <% end %>
  </div>
  <% end %>
</div>

app/views/plants/index.html.erb
<div class="plants">
  <div class="container">
    <div class="row">
      <% @plants.each do |p| %>
          <div class="col-md-4">
            <div class="card">
              <div class="card-image">
                <img class="img-responsive" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20%282%29.jpg">
                <span class="card-title"><%= p.name %></span>
              </div>

              <div class="card-content">
                <!--Title-->
                <h5 class="card-title"><b><%= p.common_names %></b></h5>
                <!--Text-->
                <p class="card-text"><%= p.description %></p>
              </div>

              <div class="card-action">
                <%= link_to 'More info', plant_path(p), class: 'btn' %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/plants/new.html.erb
<script>
    allTags = <%= raw all_tags.to_json %>;
    currentTags = <%= raw tag_list.to_json %>;
</script>

<div class="col-md-4 col-md-offset-4">
  <%= bootstrap_form_for(@plant) do |f| %>
  <div class="field">
    <%= f.text_field :name %>
    <%= f.text_field :common_names %>
    <%= f.label :common_names, 'Please separate each name with a comma' %>
  </div>
  <br>
  <div class="field">
    <%= f.number_field :watering_time %>
    <%= f.label :watering_time, 'Days between watering' %>
  </div>
  <br>
  <div class="field">
    <%= f.select :sunlight_exposure, [['Shade', 0], ['Partial Shade', 1], ['Partial Light', 2], ['Direct Light', 3]] %>
    <%= f.select :summer_environment, [['Indoors', 0], ['Outdoors', 1], ['Either', 2]] %>
    <%= f.select :winter_environment, [['Indoors', 0], ['Outdoors', 1], ['Either', 2]] %>
  </div>
  <br>
  <div class="field">
    <%= f.text_area :description %>
    <%= f.text_field :info_link %>
  </div>
  <div class="field">
    <%= f.text_field :tag_list, 'data-role'=>'tagsinput', id: 'tags' %>
    <script>
        var tagNames = new Bloodhound({
            datumTokenizer: Bloodhound.tokenizers.obj.whitespace('name'),
            queryTokenizer: Bloodhound.tokenizers.whitespace,
            local: allTags
        });

        var input = $('#tags');
        input.tagsinput({
            itemValue: 'id',
            itemText: 'name',
            maxTags: 3,
            trimValue: true,
            cancelConfirmKeysOnEmpty: true,
            typeaheadjs: {
                highlight: true,
                name: 'tags',
                display: 'name',
                source: tagNames.ttAdapter()
            }
        });

        for(var i in currentTags) input.tagsinput('add', currentTags[i]);
    </script>
  </div>
  <div class="actions">
    <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
        <i class="icon-ok icon-white"></i> Add plant
    <% end %>
  </div>
  <% end %>
</div>

app/views/plants/show.html.erb
<h1><%= @plant.name %></h1>
<p><%= @plant.description %> (<%= link_to 'More info', @plant.info_link %>)</p>
<p>Requires watering every <b><%= @plant.watering_time %></b> day<%= @plant.watering_time > 1 ? 's' : '' %></p>
<p>Tags: <% @tags.each do |t| %>
      <%= link_to t.name, tag_path(t), class: 'btn btn-default' %>
  <% end %></p>
<hr>
<%= link_to 'Delete', plant_path, method: :delete %>
|
<%= link_to 'Edit', edit_plant_path %>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <div class="col-md-4 text-left">
      <%= link_to '<i class="glyphicon glyphicon-menu-left"></i> Previous'.html_safe, calendar.url_for_previous_view, class: 'btn btn-default bottom' %>
    </div>
    <div class="col-md-4 text-center">
      <span class="calendar-title"><h4><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></h4></span>
    </div>
    <div class="col-md-4 text-right">
      <%= link_to 'Next <i class="glyphicon glyphicon-menu-right"></i>'.html_safe, calendar.url_for_next_view, class: 'btn btn-default bottom' %>
    </div>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<p>Find me in app/views/tags/edit.html.erb</p>

app/views/tags/index.html.erb
<div class="plants">
  <div class="container">
    <div class="row">
      <% @tags.each do |t| %>
          <div class="col-md-4">
            <div class="card">
              <div class="card-image">
                <img class="img-responsive" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20%282%29.jpg">
                <span class="card-title"><%= t.name %></span>
              </div>

              <div class="card-content">
                <!--Title-->
                <h5 class="card-title">Contains <b><%= t.plants.length %></b> plants</h5>
              </div>

              <div class="card-action">
                <%= link_to 'View', tag_path(t), class: 'btn' %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tags/new.html.erb
<h1>Tags#new</h1>
<p>Find me in app/views/tags/new.html.erb</p>

app/views/tags/show.html.erb
<div class="plants">
  <div class="container">
    <div class="row">
      <% @plants.each do |p| %>
          <div class="col-md-4">
            <div class="card">
              <div class="card-image">
                <img class="img-responsive" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20%282%29.jpg">
                <span class="card-title"><%= p.name %></span>
              </div>

              <div class="card-content">
                <!--Title-->
                <h5 class="card-title"><b><%= p.common_names %></b></h5>
                <!--Text-->
                <p class="card-text"><%= p.description %></p>
              </div>

              <div class="card-action">
                <%= link_to 'More info', plant_path(p), class: 'btn' %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>
<%= link_to 'Delete', tag_path, method: :delete %>
|
<%= link_to 'Edit', edit_tag_path %>

app/views/user_plants/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h3>Editing: <%= @user_plant.custom_name %></h3>
  <h4>(<%= @user_plant.plant.name %>)</h4>
  <%= bootstrap_form_for(@user_plant) do |f| %>
      <div class="field">
        <%= f.select :plant, Plant.all.collect {|p| [p.name, p.id]} %>
      </div>
      <div class="field">
        <%= f.text_field :custom_name %>
      </div>
      <br>
      <div class="field">
        <%= f.datetime_select :last_watered %>
      </div>
      <br>
      <div class="field">
        <%= f.text_area :notes %>
      </div>
      <div class="actions">
        <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
            <i class="icon-ok icon-white"></i> Save changes
        <% end %>
      </div>
  <% end %>
</div>

app/views/user_plants/index.html.erb
<%= @plants.each do |p| %>
<h1><%= p.custom_name %></h1>
<% end %>

app/views/user_plants/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <%= bootstrap_form_for(@user_plant) do |f| %>
      <div class="field">
        <%= f.select :plant, Plant.all.collect {|p| [p.name, p.id]} %>
      </div>
      <div class="field">
        <%= f.text_field :custom_name %>
      </div>
      <br>
      <div class="field">
        <%= f.datetime_select :last_watered %>
      </div>
      <br>
      <div class="field">
        <%= f.text_area :notes %>
      </div>
      <div class="actions">
        <%= button_tag(type: 'submit', class: 'btn btn-success') do %>
            <i class="icon-ok icon-white"></i> Add plant
        <% end %>
      </div>
  <% end %>
</div>

app/views/user_plants/show.html.erb
<h1><%= @user_plant.custom_name %></h1>
<h3>(<%= @user_plant.plant.name %>)</h3>
<p>Last watered <b><%= @user_plant.last_watered %></b></p>
<p>Water next at <b><%= @user_plant.last_watered + @user_plant.plant.watering_time.days %></b></p>
<p>Notes: <i><%= @user_plant.notes %></i></p>
<hr>
<%= link_to 'Delete', user_plant_path, method: :delete %>
|
<%= link_to 'Edit', edit_user_plant_path %>

app/views/users/new.html.erb
<div class="col-md-4 col-md-offset-4">
	<h1>Sign Up</h1>
	<%= bootstrap_form_for(@user) do |f| %>
		<%= f.text_field :username %>
		<%= f.password_field :password %>
		<%= f.submit "Sign Up" %>
	<% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.username %>'s plants</h1>
<div class="user_plants">
  <div class="container">
    <div class="row">
      <% @user_plants.each do |p| %>
          <div class="col-md-4">
            <div class="card">
              <div class="card-image">
                <img class="img-responsive" src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20%282%29.jpg">
                <span class="card-title"><%= p.custom_name %></span>
              </div>

              <div class="card-content">
                <!--Title-->
                <h5 class="card-title"><b><%= p.plant.name %></b></h5>
              </div>

              <div class="card-action">
                <%= link_to 'More info', user_plant_path(p), class: 'btn' %>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>
<%= link_to 'Add plant', "/users/#{@user.id}/new", class: 'btn' %>
<br>
<hr>
<%= month_calendar(events: @user_plants) do |date, events| %>
    <h4><%= date.mday %><% if events.length > 0 %> <span class="glyphicon glyphicon-leaf"></span><% end %></h4>

    <% events.each do |plant| %>
      <div>
        <b><%= plant.custom_name %></b>
        <%= plant.plant.name %>
      </div>
    <% end%>
<% end %>